name: Deploy API Canchas

on:
  push:
    branches:
      - main
    paths:
      - 'services/api-canchas/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Necesario para la autenticación OIDC con AWS
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_TO_ASSUME }} # El usuario debe crear este rol y el secreto en GitHub
          aws-region: us-east-1

      - name: Install Dependencies
        working-directory: ./services/api-canchas
        run: npm install

      - name: Deploy to AWS
        working-directory: ./services/api-canchas
        run: npx serverless deploy
