# .github/workflows/deploy.yml
name: Deploy Serverless Services to AWS

on:
  push:
    branches:
      - main # Dispara el workflow en cada push a la rama 'main'
  pull_request:
    branches:
      - main # Opcional: También se ejecuta en Pull Requests para validación

jobs:
  deploy:
    runs-on: ubuntu-latest # El entorno donde se ejecutará tu workflow

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Clona tu repositorio

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Usa la misma versión de Node.js que tus Lambdas

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Versión compatible con AWS Lambda

      - name: Install Serverless Framework (global)
        run: npm install -g serverless@3

      - name: Install Serverless Python Requirements Plugin
        run: npm install -g serverless-python-requirements

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # La región de AWS donde desplegarás todos tus servicios

      - name: Deploy all Serverless services
        # Aquí definimos un array de los directorios de tus servicios
        # Asegúrate de que estos nombres coincidan con tus carpetas reales
        run: |
          SERVICE_DIRS=(api-canchas api-pagos api-reservas api-usuarios)
          DEPLOY_STAGE="dev" # Define aquí la etapa de despliegue (dev, staging, prod)

          for service_dir in "${SERVICE_DIRS[@]}"; do
            echo "::group::Deploying service: $service_dir" # Esto crea un grupo colapsable en los logs de GitHub Actions
            
            # Verifica que el directorio existe
            if [ ! -d "$service_dir" ]; then
              echo "⚠️  Directory $service_dir does not exist, skipping..."
              echo "::endgroup::"
              continue
            fi
            
            # Navega al directorio del servicio
            cd "$service_dir"
            
            # Verifica que existe serverless.yml
            if [ ! -f "serverless.yml" ]; then
              echo "⚠️  No serverless.yml found in $service_dir, skipping deployment..."
              cd ..
              echo "::endgroup::"
              continue
            fi
            
            # Instala las dependencias según el tipo de proyecto
            if [ -f "package.json" ]; then
              echo "📦 Installing Node.js dependencies for $service_dir..."
              npm install
            elif [ -f "requirements.txt" ]; then
              echo "🐍 Installing Python dependencies for $service_dir..."
              pip install -r requirements.txt
            elif [ -f "Pipfile" ]; then
              echo "🐍 Installing Python dependencies with Pipenv for $service_dir..."
              pip install pipenv
              pipenv install --deploy
            else
              echo "ℹ️  No dependency file found for $service_dir (package.json, requirements.txt, or Pipfile)"
            fi

            # Despliega el servicio
            echo "🚀 Deploying $service_dir to AWS stage: $DEPLOY_STAGE"
            sls deploy --stage "$DEPLOY_STAGE" --verbose

            # Regresa al directorio raíz del repositorio antes de ir al siguiente servicio
            cd .. 
            echo "✅ Successfully deployed $service_dir"
            echo "::endgroup::"
          done
        # Opcional: Si tienes variables de entorno específicas para el despliegue
        # env:
        #   MY_CUSTOM_VAR: 'some_value'
